parameters:
    locale: en

imports:
    - { resource: 'services/Infrastructure/infrastructure.yaml' }
    - { resource: 'services/Domain/domain.yaml' }
    - { resource: 'services/Application/application.yaml' }